services:
  - type: web
    name: prxfm-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    rootDir: server
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: prxfm-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/health

  - type: web
    name: prxfm-frontend
    env: static
    buildCommand: cd client && npm install && npm run build
    staticPublishPath: client/build
    envVars:
      - key: REACT_APP_API_URL
        fromService:
          type: web
          name: prxfm-backend
          envVarKey: RENDER_EXTERNAL_URL
